# Generated by Django 5.1.6 on 2025-02-19 15:55

from django.db import migrations

def cargar_datos_iniciales(apps, schema_editor):
    Cargo = apps.get_model('recepcion', 'Cargo')
    Cargo.objects.create(nombre="Alcalde")
    Cargo.objects.create(nombre="Concejal")

    TipoDocumento = apps.get_model('recepcion', 'TipoDocumento')
    TipoDocumento.objects.create(nombre="No Especificado", sigla="N/E")
    TipoDocumento.objects.create(nombre="Informe", sigla="INF")

class Migration(migrations.Migration):
    dependencies = [
        ('recepcion', '0001_initial'),  # Depende de la migración inicial
    ]

    operations = [
        migrations.RunPython(cargar_datos_iniciales),
    ]