# Generated by Django 5.1.6 on 2025-02-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Dependencia')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Documento')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='Sigla del Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.dependencia', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Ente',
                'verbose_name_plural': 'Entes',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Recepción')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificación del Documento')),
                ('enlace_drive', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Google Drive')),
                ('destinatarios', models.ManyToManyField(related_name='documento_destinatarios', to='recepcion.ente', verbose_name='Destinatarios')),
                ('remitentes', models.ManyToManyField(related_name='documento_remitentes', to='recepcion.ente', verbose_name='Remitentes')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
