# Generated by Django 5.1.6 on 2025-02-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_recepcion', models.DateTimeField(verbose_name='Fecha y Hora de Recepción')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificación del Documento')),
                ('enlace_drive', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Google Drive')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Persona Jurídica', 'Persona Jurídica')], max_length=20)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Documento')),
                ('sigla', models.CharField(blank=True, max_length=255, verbose_name='Sigla del Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='EntidadDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.cargo', verbose_name='Cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_destinatario_documento', to='recepcion.entidad', verbose_name='Entidad')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.documento', verbose_name='Documento')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_destinatario_documento', to='recepcion.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.cargo', verbose_name='Cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_remitente_documento', to='recepcion.entidad', verbose_name='Entidad')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.documento', verbose_name='Documento')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_remitente_documento', to='recepcion.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.tipodocumento', verbose_name='Tipo de Documento'),
        ),
    ]
