# Generated by Django 5.1.6 on 2025-02-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidaddestinatario',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_destinatario_documento', to='recepcion.entidad', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='entidadremitente',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_remitente_documento', to='recepcion.entidad', verbose_name='Entidad'),
        ),
    ]
