# Generated by Django 5.1.6 on 2025-02-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ente',
            options={'verbose_name': 'Remitente/Destinatario', 'verbose_name_plural': 'Remitentes/Destinatarios'},
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='sigla',
            field=models.CharField(max_length=255, verbose_name='Sigla del Tipo de Documento'),
        ),
    ]
