# Generated by Django 5.1.6 on 2025-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_alter_ente_options_alter_tipodocumento_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tipo de Documento'),
        ),
    ]
