# Generated by Django 5.1.6 on 2025-02-20 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_alter_entidaddestinatario_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='enlace_drive',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='entidaddestinatario',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_destinatario_documento', to='recepcion.entidad', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='entidadremitente',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_remitente_documento', to='recepcion.entidad', verbose_name='Dependencia'),
        ),
    ]
