# Generated by Django 5.1.6 on 2025-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_alter_tipodocumento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='sigla',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sigla del Tipo de Documento'),
        ),
    ]
