# Generated by Django 5.1.6 on 2025-02-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_alter_documento_enlace_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
